use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :chup, Chup.Endpoint,
       http: [port: {:system, "PORT"}],
       url: [scheme: "https", host: "pure-tundra-60175.herokuapp.com", port: 443], # substitute your app's name
       cache_static_manifest: "priv/static/manifest.json",
       secret_key_base: System.get_env("SECRET_KEY_BASE"),
       check_origin: ["http://chup.s3-website.eu-west-3.amazonaws.com"] # substitute you frontend's domain


# Do not print debug messages in production
config :logger, level: :info

#Guardian
config :guardian, Guardian,
       secret_key: System.get_env("GUARDIAN_SECRET_KEY")

#Ecto Repo
config :chup, Chup.Repo,
       adapter: Ecto.Adapters.Postgres,
       url: System.get_env("DATABASE_URL"),
       pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
       ssl: true
